Repository aurelio-labs/semantic-router, pull requests merged in 2024-03, with the labels that each got.

#189 fix: fixes #188 ```AzureOpenAIEncoder``` issue
  semantic_router/encoders/zure.py
Labels: bug

#180 feat: Support openai base_url
  semantic_router/encoders/openai.py
Labels: enhancement

#202 feat: Support for setting aggregation for (Hybrid)RouteLayer
  coverage.xml
  semantic_router/hybrid_layer.py
  semantic_router/layer.py
  tests/unit/test_hybrid_layer.py
  tests/unit/test_layer.py
Labels: enhancement

#207 feat: QdrantIndex
  poetry.lock
  pyproject.toml
  semantic_router/index/__init__.py
  semantic_router/index/qdrant.py
  semantic_router/layer.py
  semantic_router/schema.py
  tests/unit/test_layer.py
Labels: feature

#220 chore: Reduction of logs for splitter
  semantic_router/splitters/rolling_window.py
Labels: enhancement
