Repository aurelio-labs/semantic-router, pull requests merged in 2024-02, with the labels that each got.

#153 feat: Pinecone demo and hotfix
  docs/07-scaling-and-pinecone.ipynb
  poetry.lock
  pyproject.toml
  semantic_router/__init__.py
  semantic_router/index/pinecone.py
Labels: bug, documentation

#154 chore: move pinecone demo
  docs/examples/pinecone-and-scaling.ipynb
  docs/indexes/local.ipynb
  docs/indexes/pinecone.ipynb
Labels: documentation

#165 fix: PineconeIndex upsert request size limit
  semantic_router/index/pinecone.py
Labels: bug, enhancement, feature
