Repository aurelio-labs/semantic-router, pull requests merged in 2024-10, with the labels that each got.

#436 feat: Update route thresholds manually
  semantic_router/layer.py
  tests/unit/test_layer.py
Labels: enhancement, Review effort [1-5]: 3, error handling

#440 fix: update to allow latest pinecone versions
  docs/source/conf.py
  poetry.lock
  pyproject.toml
  semantic_router/__init__.py
Labels: enhancement, Review effort [1-5]: 2, dependencies

#441 fix: pinecone version
  poetry.lock
  pyproject.toml
Labels: Review effort [1-5]: 1, dependencies

#442 chore: version fix
  docs/source/conf.py
  pyproject.toml
  semantic_router/__init__.py
Labels: enhancement, Review effort [1-5]: 1

#444 feat: is_synced method for Pinecone Index
  docs/source/route_layer/sync.rst
  semantic_router/index/base.py
  semantic_router/index/pinecone.py
  semantic_router/layer.py
Labels: enhancement, feature, Review effort [1-5]: 3

#447 chore: release v0.0.71
  docs/source/conf.py
  pyproject.toml
  semantic_router/__init__.py
Labels: documentation, enhancement, Review effort [1-5]: 1

#448 feat: move cohere to optional dep
  docs/source/conf.py
  poetry.lock
  pyproject.toml
  semantic_router/__init__.py
  semantic_router/encoders/cohere.py
  semantic_router/llms/cohere.py
  tests/unit/encoders/test_cohere.py
  tests/unit/llms/test_llm_cohere.py
Labels: enhancement, Review effort [1-5]: 3, dependencies

#456 feat: add test for 3.12 and remove 3.9
  .github/workflows/test.yml
Labels: Review effort [1-5]: 1
