Repository aurelio-labs/semantic-router, pull requests merged in 2024-01, with the labels that each got.

#68 feat: Add fastembed encoder
  poetry.lock
  pyproject.toml
  semantic_router/encoders/__init__.py
  semantic_router/encoders/fastembed.py
  test_output.txt
  tests/unit/encoders/test_fastembed.py
Labels: enhancement

#74 fix: Coventional commits for PR titles
  .github/workflows/conventional_commits.yml
  .pre-commit-config.yaml
  commitlint.config.js
Labels: ci

#75 feat: Updated function calling example
  .gitignore
  coverage.xml
  docs/examples/function_calling.ipynb
  docs/examples/test.ann
  poetry.lock
  semantic_router/encoders/__init__.py
  semantic_router/encoders/fastembed.py
  semantic_router/layer.py
  semantic_router/route.py
  semantic_router/schema.py
  semantic_router/utils/function_call.py
  semantic_router/utils/splitters.py
  tests/unit/test_layer.py
  tests/unit/test_splitters.py
Labels: documentation, enhancement

#81 feat: created fastembed and hybrid dependency groups
  .github/workflows/test.yml
  docs/00-introduction.ipynb
  docs/01-save-load-from-file.ipynb
  docs/02-dynamic-routes.ipynb
  docs/03-basic-langchain-agent.ipynb
  poetry.lock
  pyproject.toml
  semantic_router/encoders/bm25.py
  semantic_router/encoders/fastembed.py
  semantic_router/layer.py
  semantic_router/schema.py
Labels: enhancement

#92 feat: Compatible with Python 3.9
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  Makefile
  README.md
  coverage.xml
  docs/encoders/fastembed.ipynb
  docs/examples/function_calling.ipynb
  poetry.lock
  pyproject.toml
  replace.py
  semantic_router/encoders/__init__.py
  semantic_router/encoders/bm25.py
  semantic_router/encoders/cohere.py
  semantic_router/encoders/fastembed.py
  semantic_router/encoders/huggingface.py
  semantic_router/encoders/openai.py
  semantic_router/hybrid_layer.py
  semantic_router/layer.py
  semantic_router/llms/base.py
  semantic_router/llms/cohere.py
  semantic_router/llms/openai.py
  semantic_router/llms/openrouter.py
  semantic_router/route.py
  semantic_router/schema.py
  semantic_router/utils/llm.py
  test_output.txt
  tests/unit/encoders/test_huggingface.py
Labels: bug, ci

#38 feat: Add tfidf
  .env.example
  LICENSE
  docs/examples/hybrid-layer.ipynb
  poetry.lock
  semantic_router/encoders/__init__.py
  semantic_router/encoders/tfidf.py
  semantic_router/hybrid_layer.py
  tests/unit/encoders/test_bm25.py
  tests/unit/encoders/test_tfidf.py
  tests/unit/test_hybrid_layer.py
Labels: enhancement

#119 chore: update README.md and add course
  README.md
Labels: documentation

#127 fix: colab conflict fix
  docs/00-introduction.ipynb
  docs/01-save-load-from-file.ipynb
  docs/02-dynamic-routes.ipynb
  docs/03-basic-langchain-agent.ipynb
  docs/05-local-execution.ipynb
  docs/06-threshold-optimization.ipynb
  docs/encoders/fastembed.ipynb
  docs/encoders/huggingface.ipynb
  docs/encoders/openai-embed-3.ipynb
  poetry.lock
  pyproject.toml
  semantic_router/__init__.py
Labels: bug
