Repository aurelio-labs/semantic-router, pull requests merged in 2024-07, with the labels that each got.

#338 chore: add license to pyproject
  pyproject.toml
Labels: enhancement, Review effort [1-5]: 1, other

#339 chore: update versions and fix license
  pyproject.toml
  semantic_router/__init__.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#344 feat: add sync setting parameter to index
  pyproject.toml
  semantic_router/index/base.py
  semantic_router/index/local.py
  semantic_router/index/pinecone.py
  semantic_router/index/qdrant.py
  semantic_router/layer.py
Labels: enhancement, Review effort [1-5]: 4

#352 feat: add init_async_index param
  pyproject.toml
  semantic_router/index/base.py
  semantic_router/index/pinecone.py
Labels: enhancement, Review effort [1-5]: 2, Configuration changes

#353 fix: docs outdated
  docs/indexes/pinecone_async.ipynb
Labels: documentation, enhancement, Review effort [1-5]: 1

#355 feat: add sparse vector for PineconeIndex
  pyproject.toml
  semantic_router/__init__.py
  semantic_router/index/local.py
  semantic_router/index/pinecone.py
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#356 feat: integrate the OpenAILLM async into the RL
  docs/08-async-dynamic-routes.ipynb
  pyproject.toml
  semantic_router/__init__.py
  semantic_router/layer.py
  semantic_router/llms/openai.py
  semantic_router/route.py
  semantic_router/utils/defaults.py
  tests/unit/llms/test_llm_azure_openai.py
  tests/unit/llms/test_llm_openai.py
  tests/unit/test_hybrid_layer.py
  tests/unit/test_layer.py
Labels: documentation, enhancement, Review effort [1-5]: 3

#358 fix: handling non-existing local routes in sync
  semantic_router/index/pinecone.py
  semantic_router/layer.py
Labels: enhancement, Review effort [1-5]: 4, Bug fix
