Repository aurelio-labs/semantic-router, pull requests merged in 2024-12, with the labels that each got.

#472 feat: add 313 testing and upgrade pydantic
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .python-version
  .readthedocs.yaml
  LICENSE
  Makefile
  poetry.lock
  pyproject.toml
  semantic_router/encoders/aurelio.py
  semantic_router/encoders/base.py
  semantic_router/encoders/clip.py
  semantic_router/encoders/cohere.py
  semantic_router/encoders/fastembed.py
  semantic_router/encoders/huggingface.py
  semantic_router/encoders/mistral.py
  semantic_router/encoders/openai.py
  semantic_router/encoders/vit.py
  semantic_router/index/base.py
  semantic_router/index/pinecone.py
  semantic_router/index/postgres.py
  semantic_router/index/qdrant.py
  semantic_router/llms/base.py
  semantic_router/llms/cohere.py
  semantic_router/llms/llamacpp.py
  semantic_router/llms/mistral.py
  semantic_router/llms/ollama.py
  semantic_router/llms/openai.py
  semantic_router/llms/openrouter.py
  semantic_router/llms/zure.py
  semantic_router/route.py
  semantic_router/routers/base.py
  semantic_router/routers/hybrid.py
  semantic_router/schema.py
  semantic_router/utils/function_call.py
  tests/integration/encoders/test_openai_integration.py
  tests/unit/encoders/test_clip.py
  tests/unit/encoders/test_fastembed.py
  tests/unit/encoders/test_hfendpointencoder.py
  tests/unit/encoders/test_huggingface.py
  tests/unit/encoders/test_mistral.py
  tests/unit/encoders/test_openai.py
  tests/unit/encoders/test_vit.py
  tests/unit/llms/test_llm_azure_openai.py
  tests/unit/llms/test_llm_llamacpp.py
  tests/unit/llms/test_llm_ollama.py
  tests/unit/llms/test_llm_openai.py
  tests/unit/llms/test_llm_openrouter.py
  tests/unit/test_schema.py
Labels: feature, Review effort [1-5]: 2

#473 fix: sort func schemas and metadata in diffs
  semantic_router/schema.py
  tests/unit/test_sync.py
Labels: Review effort [1-5]: 2

#474 chore: new dev release
  docs/00-introduction.ipynb
  docs/examples/hybrid-router.ipynb
  docs/indexes/pinecone-sync-routes.ipynb
  docs/source/conf.py
  pyproject.toml
  semantic_router/__init__.py
Labels: Review effort [1-5]: 2

#476 fix: missing auto_sync in intro doc
  docs/00-introduction.ipynb
Labels: Review effort [1-5]: 1

#485 feat: add sync lock
  semantic_router/index/base.py
  semantic_router/index/pinecone.py
  semantic_router/routers/base.py
  semantic_router/schema.py
  tests/unit/test_sync.py
Labels: Review effort [1-5]: 4

#488 feat: add test for single route single utterance
  tests/unit/test_router.py
Labels: Review effort [1-5]: 2

#489 fix: vector shape for single utterance
  docs/source/conf.py
  pyproject.toml
  semantic_router/__init__.py
  semantic_router/routers/base.py
  semantic_router/routers/hybrid.py
  semantic_router/routers/semantic.py
  tests/unit/test_router.py
Labels: Review effort [1-5]: 2

#490 fix: Fixed namespace missing in _async_fetch_metadata inside Pinecone
  semantic_router/index/pinecone.py
Labels: bug, Review effort [1-5]: 2

#491 chore: upgrade to dev5
  docs/source/conf.py
  pyproject.toml
  semantic_router/__init__.py
Labels: Review effort [1-5]: 1

#487 feat: async sync and pinecone methods
  semantic_router/index/base.py
  semantic_router/index/pinecone.py
  semantic_router/routers/base.py
  tests/unit/test_sync.py
Labels: Review effort [1-5]: 4
