Repository aurelio-labs/semantic-router, pull requests merged in 2024-09, with the labels that each got.

#407 chore: change docs workflow temp
  .github/workflows/docs.yml
  docs/source/route_layer/dynamic-routes.rst
  docs/source/route_layer/local-execution.rst
  docs/source/route_layer/route-filter.rst
  docs/source/route_layer/route_filter.rst
  docs/source/route_layer/save-load-from-file.rst
  docs/source/route_layer/sync.rst
  docs/source/route_layer/threshold-optimization.rst
  poetry.lock
  pyproject.toml
Labels: Review effort [1-5]: 1, Configuration changes

#408 fix: nltk
  .github/workflows/test.yml
Labels: enhancement, Review effort [1-5]: 1

#391 feat: optimize local/remote routes flow and store them on Pinecone
  .gitignore
  semantic_router/index/base.py
  semantic_router/index/local.py
  semantic_router/index/pinecone.py
  semantic_router/index/postgres.py
  semantic_router/index/qdrant.py
  semantic_router/layer.py
  semantic_router/route.py
  tests/unit/test_route.py
Labels: enhancement, Review effort [1-5]: 3

#409 chore: release v0.0.63
  docs/source/conf.py
  pyproject.toml
  semantic_router/__init__.py
Labels: enhancement, Review effort [1-5]: 1

#415 fix: bug in pinecone index for func schema
  docs/source/conf.py
  pyproject.toml
  semantic_router/__init__.py
  semantic_router/index/pinecone.py
Labels: documentation, Review effort [1-5]: 2, Bug fix, other

#417 chore: release v0.0.65
  docs/source/conf.py
  pyproject.toml
  semantic_router/__init__.py
Labels: enhancement, Review effort [1-5]: 1

#414 fix: Fixed pinecone tests
  Makefile
  semantic_router/index/pinecone.py
  semantic_router/layer.py
  tests/unit/test_layer.py
Labels: Review effort [1-5]: 4, Bug fix, Tests

#427 refactor: Use Qdrant's Query API
  poetry.lock
  pyproject.toml
  semantic_router/index/qdrant.py
Labels: enhancement, Review effort [1-5]: 2, dependencies

#428 chore: v0.0.66
  README.md
  docs/source/conf.py
  pyproject.toml
  semantic_router/__init__.py
Labels: documentation, enhancement, Review effort [1-5]: 1

#431 fix: cohere type
  poetry.lock
  pyproject.toml
  semantic_router/encoders/cohere.py
Labels: Review effort [1-5]: 2, Bug fix
