Repository aurelio-labs/semantic-router, pull requests merged in 2024-05, with the labels that each got.

#266 fix: video splitter -> type error
  docs/00-introduction.ipynb
  semantic_router/encoders/openai.py
  semantic_router/schema.py
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#270 fix: add namespace to get all for pinecone
  semantic_router/index/pinecone.py
Labels: Review effort [1-5]: 2, bug_fix

#277 feat: Adding BedrockEncoder
  docs/encoders/bedrock.ipynb
  poetry.lock
  pyproject.toml
  semantic_router/encoders/__init__.py
  semantic_router/encoders/bedrock.py
  semantic_router/schema.py
  semantic_router/utils/defaults.py
  tests/unit/encoders/test_bedrock.py
Labels: documentation, enhancement, Review effort [1-5]: 4

#278 fix: Use 'api_key' parameter if passed explicitly
  semantic_router/index/pinecone.py
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#279 chore: v0.0.40 release
  pyproject.toml
  semantic_router/__init__.py
Labels: enhancement, Review effort [1-5]: 1

#280 fix: Cohere to v5
  poetry.lock
  pyproject.toml
  semantic_router/encoders/cohere.py
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#281 chore: v0.0.41 release
  docs/encoders/bedrock.ipynb
  pyproject.toml
  semantic_router/__init__.py
Labels: enhancement, Review effort [1-5]: 2

#282 chore: splitters deprecation warning
  poetry.lock
  pyproject.toml
  semantic_router/__init__.py
  semantic_router/splitters/consecutive_sim.py
  semantic_router/splitters/cumulative_sim.py
  semantic_router/splitters/rolling_window.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#289 fix: tiktoken dep
  poetry.lock
  pyproject.toml
  semantic_router/__init__.py
Labels: enhancement, Review effort [1-5]: 2

#295 fix: OpenAIEncoder, tests, and docs
  .gitignore
  docs/02-dynamic-routes.ipynb
  docs/encoders/openai-encoder.ipynb
  docs/examples/function_calling.ipynb
  docs/examples/unstructured-element-splitter.ipynb
  poetry.lock
  pyproject.toml
  semantic_router/encoders/openai.py
  tests/integration/encoders/test_openai_integration.py
Labels: documentation, enhancement, Review effort [1-5]: 3, Tests

#296 chore: update version
  pyproject.toml
  semantic_router/__init__.py
  semantic_router/encoders/openai.py
Labels: enhancement, Review effort [1-5]: 2

#303 fix: local package dep fix
  poetry.lock
  pyproject.toml
  semantic_router/__init__.py
  tests/unit/encoders/test_fastembed.py
Labels: bug, enhancement, Review effort [1-5]: 2, Bug fix
