Repository aurelio-labs/semantic-router, pull requests merged in 2024-04, with the labels that each got.

#226 fix: Pinecone PyTest env var
  .github/workflows/test.yml
  tests/unit/test_layer.py
Labels: bug

#229 chore: add source to pinecone index
  README.md
  semantic_router/index/pinecone.py
Labels: enhancement

#249 fix: Hard split for max token size
  semantic_router/splitters/rolling_window.py
Labels: bug

#262 chore: v0.0.36 release
  docs/00-introduction.ipynb
  pyproject.toml
  semantic_router/__init__.py
Labels: enhancement, Review effort [1-5]: 2

#263 fix: James/encoder disallowed special
  pyproject.toml
  semantic_router/__init__.py
  semantic_router/encoders/openai.py
Labels: enhancement, Review effort [1-5]: 2, bug_fix
