Repository aurelio-labs/semantic-router, pull requests merged in 2024-08, with the labels that each got.

#365 feat: Optimize sync embeddings
  semantic_router/index/base.py
  semantic_router/index/local.py
  semantic_router/index/pinecone.py
  semantic_router/index/qdrant.py
  semantic_router/layer.py
Labels: enhancement

#368 feat: initial sphinx pages for readthedocs
  docs/Makefile
  docs/build/doctrees/environment.pickle
  docs/build/doctrees/index.doctree
  docs/build/html/.buildinfo
  docs/build/html/_sources/index.rst.txt
  docs/build/html/_static/alabaster.css
  docs/build/html/_static/basic.css
  docs/build/html/_static/custom.css
  docs/build/html/_static/doctools.js
  docs/build/html/_static/documentation_options.js
  docs/build/html/_static/file.png
  docs/build/html/_static/language_data.js
  docs/build/html/_static/minus.png
  docs/build/html/_static/plus.png
  docs/build/html/_static/pygments.css
  docs/build/html/_static/searchtools.js
  docs/build/html/_static/sphinx_highlight.js
  docs/build/html/genindex.html
  docs/build/html/index.html
  docs/build/html/objects.inv
  docs/build/html/search.html
  docs/build/html/searchindex.js
  docs/make.bat
  docs/source/conf.py
  docs/source/index.rst
  docs/source/quickstart.rst
  poetry.lock
  pyproject.toml
Labels: documentation, enhancement, Review effort [1-5]: 3

#369 fix: readthedocs build
  .readthedocs.yaml
  docs/build/doctrees/environment.pickle
  docs/build/doctrees/index.doctree
  docs/build/doctrees/quickstart.doctree
  docs/build/html/.buildinfo
  docs/build/html/_sources/index.rst.txt
  docs/build/html/_sources/quickstart.rst.txt
  docs/build/html/genindex.html
  docs/build/html/index.html
  docs/build/html/objects.inv
  docs/build/html/quickstart.html
  docs/build/html/search.html
  docs/build/html/searchindex.js
Labels: documentation, Review effort [1-5]: 2

#370 feat: sphinx mods
  .gitignore
  .readthedocs.yaml
  docs/build/doctrees/environment.pickle
  docs/build/doctrees/index.doctree
  docs/build/doctrees/quickstart.doctree
  docs/build/html/.buildinfo
  docs/build/html/_sources/index.rst.txt
  docs/build/html/_sources/quickstart.rst.txt
  docs/build/html/_static/alabaster.css
  docs/build/html/_static/basic.css
  docs/build/html/_static/custom.css
  docs/build/html/_static/doctools.js
  docs/build/html/_static/documentation_options.js
  docs/build/html/_static/file.png
  docs/build/html/_static/language_data.js
  docs/build/html/_static/minus.png
  docs/build/html/_static/plus.png
  docs/build/html/_static/pygments.css
  docs/build/html/_static/searchtools.js
  docs/build/html/_static/sphinx_highlight.js
  docs/build/html/genindex.html
  docs/build/html/index.html
  docs/build/html/objects.inv
  docs/build/html/quickstart.html
  docs/build/html/search.html
  docs/build/html/searchindex.js
  docs/source/conf.py
  docs/source/index.rst
  docs/source/requirements.txt
  poetry.lock
  pyproject.toml
Labels: documentation, enhancement, Review effort [1-5]: 2

#347 feat: postgres db
  docs/indexes/postgres/Dockerfile
  docs/indexes/postgres/postgres.compose.yaml
  docs/indexes/postgres/postgres.ipynb
  poetry.lock
  pyproject.toml
  semantic_router/index/postgres.py
Labels: documentation, enhancement, Review effort [1-5]: 4, Tests

#375 feat: Added local execution for layer fitting
  semantic_router/index/base.py
  semantic_router/layer.py
Labels: enhancement, Review effort [1-5]: 3

#379 fix: most postgres installs to optional
  docs/source/conf.py
  poetry.lock
  pyproject.toml
  semantic_router/__init__.py
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#381 feat: add ollama signature builder
  docs/source/conf.py
  pyproject.toml
  semantic_router/__init__.py
  semantic_router/utils/function_call.py
  tests/unit/test_function_schema.py
Labels: enhancement, Review effort [1-5]: 3, Tests

#389 feat: add max_retries to OpenAI and Azure encoders
  semantic_router/encoders/openai.py
  semantic_router/encoders/zure.py
  semantic_router/utils/function_call.py
  tests/integration/encoders/test_openai_integration.py
  tests/unit/encoders/test_azure.py
  tests/unit/encoders/test_openai.py
Labels: enhancement, Review effort [1-5]: 3

#390 chore: v0.0.60
  docs/source/conf.py
  pyproject.toml
  semantic_router/__init__.py
Labels: enhancement, Review effort [1-5]: 1

#397 feat: Implemented aget_routes async method for pinecone index
  docs/source/conf.py
  pyproject.toml
  semantic_router/__init__.py
  semantic_router/index/base.py
  semantic_router/index/local.py
  semantic_router/index/pinecone.py
  semantic_router/index/postgres.py
  semantic_router/index/qdrant.py
  tests/unit/encoders/test_vit.py
Labels: enhancement, Review effort [1-5]: 3

#398 fix: tests and errors messages
  semantic_router/encoders/vit.py
  tests/unit/encoders/test_vit.py
Labels: Review effort [1-5]: 2, Bug fix, Tests

#394 fix: namespace in sync routes deletion
  semantic_router/index/pinecone.py
Labels: enhancement, Bug fix, Review effort [1-5]: 1

#403 feat: Use Pinecone library list functionality
  semantic_router/index/pinecone.py
Labels: enhancement, Review effort [1-5]: 2

#404 chore: release v0.0.62
  docs/source/conf.py
  pyproject.toml
  semantic_router/__init__.py
Labels: enhancement, Review effort [1-5]: 1

#405 feat: add docs workflow file
  .github/workflows/docs.yml
Labels: documentation, enhancement, Review effort [1-5]: 2
