Repository aurelio-labs/semantic-router, pull requests merged in 2025-03, with the labels that each got.

#539 feat: change version and add migration doc
  docs/examples/hybrid-router.ipynb
  docs/source/migration_to_v1.rst
  docs/source/route_layer/sync.rst
  pyproject.toml
  uv.lock
Labels: Review effort 2/5

#542 fix: release workflow
  .github/workflows/release.yml
Labels: ci, Review effort 2/5

#545 feat: azure openai updates
  docs/source/conf.py
  pyproject.toml
  semantic_router/__init__.py
  semantic_router/encoders/__init__.py
  semantic_router/encoders/azure_openai.py
  tests/unit/encoders/test_azure.py
  uv.lock
Labels: feature, Review effort 3/5

#547 fix: update release workflow and add migrration info
  .github/workflows/diff.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .github/workflows/triggers_merge.yml
  .github/workflows/triggers_pr.yml
  docs/source/migration_to_v1.rst
Labels: Review effort 1/5

#549 fix: workflows
  .github/workflows/triggers_merge.yml
  .github/workflows/triggers_pr.yml
  diff-config.yaml
Labels: Review effort 2/5

#550 feat: new docs and updates
  docs/00-introduction.ipynb
  docs/01-save-load-from-file.ipynb
  docs/02-dynamic-routes.ipynb
  docs/03-basic-langchain-agent.ipynb
  docs/06-threshold-optimization.ipynb
  docs/08-async-dynamic-routes.ipynb
  docs/09-route-filter.ipynb
  docs/indexes/pinecone-async.ipynb
  docs/indexes/pinecone-local.ipynb
  docs/indexes/pinecone-sync-routes.ipynb
  docs/indexes/pinecone.ipynb
  docs/indexes/pinecone_async.ipynb
Labels: documentation, Review effort 2/5

#551 fix: docs workflows
  .github/workflows/docs.yml
  .github/workflows/triggers_merge.yml
  docs/indexes/local.ipynb
Labels: Review effort 1/5

#553 fix: add root docs
  .github/workflows/docs.yml
  docs/quickstart.md
  docs/route_layer.md
  docs/source/quickstart.rst
Labels: Review effort 2/5

#554 fix: tweaks to docstrings
  semantic_router/encoders/azure_openai.py
  semantic_router/encoders/bm25.py
Labels: Review effort 1/5

#556 fix: dir and markdown
  .github/workflows/docs.yml
  docs/essentials/dynamic-routes.md
  docs/essentials/local-execution.md
  docs/essentials/migration-to-v1.md
  docs/essentials/quickstart.md
  docs/essentials/route-filter.md
  docs/essentials/save-load-from-file.md
  docs/essentials/semantic-router.md
  docs/essentials/sync.md
  docs/essentials/threshold-optimization.md
  docs/source/route_layer/dynamic-routes.rst
  docs/source/route_layer/local-execution.rst
  docs/source/route_layer/route-filter.rst
  docs/source/route_layer/save-load-from-file.rst
  docs/source/route_layer/sync.rst
  docs/source/route_layer/threshold-optimization.rst
Labels: Review effort 3/5

#564 feat: improved hybrid router doc
  docs/examples/hybrid-router.ipynb
Labels: documentation

#565 fix: threshold issue
  docs/00-introduction.ipynb
  docs/01-save-load-from-file.ipynb
  docs/02-dynamic-routes.ipynb
  docs/03-basic-langchain-agent.ipynb
  docs/06-threshold-optimization.ipynb
  docs/08-async-dynamic-routes.ipynb
  docs/09-route-filter.ipynb
  docs/examples/hybrid-router.ipynb
  docs/indexes/local.ipynb
  docs/indexes/pinecone-local.ipynb
  docs/indexes/pinecone-sync-routes.ipynb
  docs/indexes/pinecone.ipynb
  docs/indexes/pinecone_async.ipynb
  docs/user-guide/features/dynamic-routes.md
  docs/user-guide/features/threshold-optimization.md
  pyproject.toml
  semantic_router/__init__.py
  semantic_router/routers/hybrid.py
  uv.lock
Labels: Review effort 3/5

#566 feat: enable multi routes for v0.1
  .github/workflows/test.yml
  .github/workflows/triggers_pr.yml
  docs/00-introduction.ipynb
  docs/01-save-load-from-file.ipynb
  docs/02-dynamic-routes.ipynb
  docs/03-basic-langchain-agent.ipynb
  docs/06-threshold-optimization.ipynb
  docs/08-async-dynamic-routes.ipynb
  docs/09-route-filter.ipynb
  docs/indexes/local.ipynb
  docs/indexes/pinecone-local.ipynb
  docs/indexes/pinecone-sync-routes.ipynb
  docs/indexes/pinecone.ipynb
  docs/indexes/pinecone_async.ipynb
  docs/user-guide/features/dynamic-routes.md
  docs/user-guide/features/threshold-optimization.md
  docs/user-guide/guides/migration-to-v1.md
  pyproject.toml
  semantic_router/encoders/bm25.py
  semantic_router/encoders/openai.py
  semantic_router/routers/base.py
  semantic_router/routers/hybrid.py
  tests/functional/encoders/test_bm25_functional.py
  tests/integration/encoders/test_openai_integration.py
  tests/unit/encoders/test_bm25.py
  tests/unit/test_router.py
  tests/unit/test_tokenizers.py
  uv.lock
Labels: Review effort 4/5

#567 fix: threshold set
  docs/00-introduction.ipynb
  docs/01-save-load-from-file.ipynb
  docs/02-dynamic-routes.ipynb
  docs/03-basic-langchain-agent.ipynb
  docs/06-threshold-optimization.ipynb
  docs/08-async-dynamic-routes.ipynb
  docs/09-route-filter.ipynb
  docs/indexes/local.ipynb
  docs/indexes/pinecone-local.ipynb
  docs/indexes/pinecone-sync-routes.ipynb
  docs/indexes/pinecone.ipynb
  docs/indexes/pinecone_async.ipynb
  docs/user-guide/features/dynamic-routes.md
  docs/user-guide/features/threshold-optimization.md
  docs/user-guide/guides/migration-to-v1.md
  pyproject.toml
  semantic_router/routers/base.py
  uv.lock
Labels: Review effort 3/5

#569 feat: add note on top_k to migration doc
  docs/user-guide/guides/migration-to-v1.md
Labels: Review effort 1/5

#570 fix: dep issue
  .github/workflows/test.yml
  docs/00-introduction.ipynb
  docs/01-save-load-from-file.ipynb
  docs/02-dynamic-routes.ipynb
  docs/03-basic-langchain-agent.ipynb
  docs/06-threshold-optimization.ipynb
  docs/08-async-dynamic-routes.ipynb
  docs/09-route-filter.ipynb
  docs/indexes/local.ipynb
  docs/indexes/pinecone-local.ipynb
  docs/indexes/pinecone-sync-routes.ipynb
  docs/indexes/pinecone.ipynb
  docs/indexes/pinecone_async.ipynb
  docs/user-guide/features/dynamic-routes.md
  docs/user-guide/features/threshold-optimization.md
  docs/user-guide/guides/migration-to-v1.md
  pyproject.toml
  semantic_router/tokenizers.py
  uv.lock
Labels: Review effort 3/5

#572 fix: aurelio sdk version
  pyproject.toml
  uv.lock
Labels: Review effort 1/5
