Repository aurelio-labs/semantic-router, pull requests merged in 2025-04, with the labels that each got.

#574 feat: reduce deps
  Makefile
  docs/00-introduction.ipynb
  docs/01-save-load-from-file.ipynb
  docs/02-dynamic-routes.ipynb
  docs/03-basic-langchain-agent.ipynb
  docs/05-local-execution.ipynb
  docs/06-threshold-optimization.ipynb
  docs/08-async-dynamic-routes.ipynb
  docs/09-route-filter.ipynb
  docs/encoders/openai-encoder.ipynb
  docs/examples/hybrid-chat-guardrails.ipynb
  docs/examples/ollama-local-execution.ipynb
  docs/indexes/local.ipynb
  docs/indexes/pinecone-async.ipynb
  docs/indexes/pinecone-local.ipynb
  docs/indexes/pinecone.ipynb
  docs/indexes/pinecone_async.ipynb
  docs/indexes/postgres/postgres.ipynb
  docs/indexes/qdrant.ipynb
  docs/integrations/pydantic-ai/chatbot-with-guardrails.ipynb
  pyproject.toml
  semantic_router/encoders/huggingface.py
  semantic_router/index/pinecone.py
  semantic_router/routers/base.py
  semantic_router/tokenizers.py
  tests/functional/encoders/test_bm25_functional.py
  tests/unit/encoders/test_bedrock.py
  tests/unit/encoders/test_bm25.py
  tests/unit/encoders/test_cohere.py
  tests/unit/encoders/test_google.py
  tests/unit/llms/test_llm_azure_openai.py
  tests/unit/llms/test_llm_base.py
  tests/unit/llms/test_llm_openai.py
  tests/unit/llms/test_llm_openrouter.py
  tests/unit/test_router.py
  uv.lock
Labels: Review effort 4/5

#580 feat: mistral litellm encoder mitigation
  docs/encoders/mistral-encoder.ipynb
  semantic_router/encoders/mistral.py
Labels: Review effort 3/5

#581 feat: voyage/jina_ai encoder addition
  docs/encoders/jina-encoder.ipynb
  docs/encoders/mistral-encoder.ipynb
  docs/encoders/voyage-encoder.ipynb
  semantic_router/encoders/__init__.py
  semantic_router/encoders/jina.py
  semantic_router/encoders/voyage.py
  semantic_router/schema.py
  semantic_router/utils/defaults.py
  tests/unit/encoders/test_lite_encoders.py
Labels: Review effort 4/5

#584 fix: docs link
  README.md
Labels: documentation

#587 fix: pg get utterances
  .gitignore
  semantic_router/index/postgres.py
Labels: Review effort 2/5
