Repository aurelio-labs/semantic-router, pull requests merged in 2025-06, with the labels that each got.

#571 docs(notebook): Sparse threshold optimization with GraphAI notebook
  docs/integrations/graphai/sparse-threshold-optimization-guardrail-graphai.ipynb
Labels: Review effort 5/5

#582 feat: nvidia_nim encoder
  docs/encoders/nvidia_nim-encoder.ipynb
  semantic_router/encoders/__init__.py
  semantic_router/encoders/litellm.py
  semantic_router/encoders/nvidia_nim.py
  semantic_router/schema.py
  semantic_router/utils/defaults.py
  tests/unit/encoders/test_lite_encoders.py
Labels: Review effort 3/5

#597 feat: psycopg 3.1.0 update
  .env.example
  .github/workflows/test.yml
  docs/examples/ollama-local-execution.ipynb
  docs/indexes/postgres-sync.ipynb
  docs/integrations/graphai/sparse-threshold-optimization-guardrail-graphai.ipynb
  docs/user-guide/changelog.md
  pyproject.toml
  semantic_router/index/base.py
  semantic_router/index/postgres.py
  semantic_router/routers/base.py
  tests/integration/test_router_integration.py
  tests/unit/test_router.py
  uv.lock
Labels: Review effort 4/5

#602 feat: update tests to not run integration test for forks
  .github/workflows/test.yml
  .github/workflows/triggers_pr.yml
  CLAUDE.md
  docs/user-guide/changelog.md
  docs/user-guide/guides/configuration.md
  semantic_router/index/base.py
  semantic_router/index/local.py
  semantic_router/index/pinecone.py
  semantic_router/index/postgres.py
  semantic_router/index/qdrant.py
  semantic_router/utils/logger.py
  tests/unit/test_router.py
Labels: Review effort 2/5

#612 fix: pinecone async init
  semantic_router/index/pinecone.py
  semantic_router/routers/base.py
Labels: Review effort 3/5
