Repository aurelio-labs/semantic-router, pull requests merged in 2025-07, with the labels that each got.

#618 feat: added async functions and fixed duplication bug
  semantic_router/index/qdrant.py
  tests/unit/test_router.py
Labels: Review effort 2/5

#619 feat: sync test compatable
  semantic_router/index/qdrant.py
  tests/unit/test_sync.py
Labels: Review effort 3/5

#620 docs(notebook): Semantic and Hybrid Router with Agents SDK Guardrails 2
  docs/integrations/agents-sdk/hybrid-router-guardrails.ipynb
  docs/integrations/agents-sdk/semantic-router-guardrail.ipynb
Labels: Review effort 3/5

#621 feat: optimize sync test
  tests/unit/test_sync.py
Labels: Review effort 4/5

#629 chore: add changelog info for v0.1.10
  docs/user-guide/changelog.md
Labels: Review effort 1/5
