Repository aurelio-labs/semantic-router, pull requests merged in 2025-02, with the labels that each got.

#524 fix: handle empty function_schemas in route processing
  semantic_router/routers/base.py
Labels: Review effort [1-5]: 2

#522 feat: Add Pinecone Local Index support and update dependencies
  .github/workflows/test.yml
  .gitignore
  CONTRIBUTING.md
  Makefile
  docs/indexes/pinecone-local.ipynb
  poetry.lock
  pyproject.toml
  semantic_router/index/pinecone.py
  semantic_router/routers/base.py
  semantic_router/schema.py
  tests/unit/test_router.py
  tests/unit/test_sync.py
Labels: Review effort [1-5]: 5

#531 fix: pinecone init logic
  docs/source/conf.py
  pyproject.toml
  semantic_router/__init__.py
  semantic_router/index/pinecone.py
  semantic_router/routers/base.py
  tests/unit/test_router.py
Labels: Review effort [1-5]: 4

#533 chore: add docstrings for indexes and routers
  semantic_router/encoders/aurelio.py
  semantic_router/encoders/base.py
  semantic_router/encoders/bedrock.py
  semantic_router/encoders/clip.py
  semantic_router/encoders/cohere.py
  semantic_router/encoders/fastembed.py
  semantic_router/encoders/google.py
  semantic_router/encoders/huggingface.py
  semantic_router/encoders/mistral.py
  semantic_router/encoders/openai.py
  semantic_router/encoders/vit.py
  semantic_router/encoders/zure.py
  semantic_router/index/base.py
  semantic_router/index/hybrid_local.py
  semantic_router/index/local.py
  semantic_router/index/pinecone.py
  semantic_router/index/postgres.py
  semantic_router/index/qdrant.py
  semantic_router/linear.py
  semantic_router/llms/base.py
  semantic_router/llms/cohere.py
  semantic_router/llms/llamacpp.py
  semantic_router/llms/mistral.py
  semantic_router/llms/ollama.py
  semantic_router/llms/openai.py
  semantic_router/llms/openrouter.py
  semantic_router/llms/zure.py
  semantic_router/route.py
  semantic_router/routers/base.py
  semantic_router/routers/hybrid.py
  semantic_router/routers/semantic.py
  semantic_router/schema.py
  semantic_router/utils/defaults.py
  semantic_router/utils/function_call.py
  semantic_router/utils/llm.py
  semantic_router/utils/logger.py
Labels: Review effort [1-5]: 2

#535 feat: add async delete support
  semantic_router/index/base.py
  semantic_router/index/pinecone.py
  semantic_router/routers/base.py
Labels: feature, Review effort 4/5

#537 feat: uv migration
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  poetry.lock
  pyproject.toml
  uv.lock
Labels: Review effort 4/5

#536 chore: update docs generation
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .pydoc-markdown.yml
  Makefile
  docs/indexes/postgres/postgres.ipynb
  pyproject.toml
  semantic_router/encoders/bedrock.py
  semantic_router/index/pinecone.py
  semantic_router/routers/hybrid.py
  semantic_router/routers/semantic.py
  tests/unit/test_router.py
  tests/unit/test_sync.py
  uv.lock
Labels: Review effort 4/5

#528 feat: implements vectorised sparse BM25 encoder
  coverage.xml
  pyproject.toml
  semantic_router/encoders/aurelio.py
  semantic_router/encoders/base.py
  semantic_router/encoders/bm25.py
  semantic_router/encoders/cohere.py
  semantic_router/encoders/encode_input_type.py
  semantic_router/encoders/huggingface.py
  semantic_router/encoders/tfidf.py
  semantic_router/routers/base.py
  semantic_router/routers/hybrid.py
  semantic_router/routers/semantic.py
  semantic_router/schema.py
  semantic_router/tokenizers.py
  tests/functional/encoders/test_bm25_functional.py
  tests/unit/encoders/test_bm25.py
  tests/unit/encoders/test_huggingface.py
  tests/unit/test_router.py
  tests/unit/test_sync.py
  tests/unit/test_tokenizers.py
  uv.lock
Labels: Review effort [1-5]: 5

#500 fix: updates semantic version on docs
  docs/01-save-load-from-file.ipynb
  docs/02-dynamic-routes.ipynb
  docs/03-basic-langchain-agent.ipynb
  docs/06-threshold-optimization.ipynb
  docs/08-async-dynamic-routes.ipynb
  docs/09-route-filter.ipynb
Labels: Review effort [1-5]: 4

#496 fix: updated async doc to use up-to-date semantic router version
  docs/indexes/pinecone_async.ipynb
Labels: Review effort [1-5]: 1

#504 feat: fixed encoders docs to use semantic router v 0.1.0
  docs/encoders/fastembed.ipynb
  docs/encoders/google.ipynb
  docs/encoders/huggingface-endpoint.ipynb
  docs/encoders/huggingface.ipynb
  docs/encoders/openai-embed-3.ipynb
Labels: Review effort [1-5]: 2

#505 feat: updated readme file to use semantic router
  README.md
Labels: Review effort [1-5]: 1

#502 feat: updated index docs
  docs/indexes/local.ipynb
  docs/indexes/pinecone.ipynb
Labels: Review effort [1-5]: 4
